### ISSUE TITLE
Multiple imports of web components

### ISSUE THREAD

**Issue by 64BitAsura** [ArcBees/gwt-polymer#6]
Using the import interface - multiple web components are injected into the HTML DOM via <link> tag. For each, imports unnecessary resource loading latencys are introduced - instead if we vulcanize it into a single html file - improves the rendering speed of page :)

**Comment by meriouma** [comment]
Agreed, this was on our roadmap ;)

**Comment by 64BitAsura** [comment]
I love to contribute, but I need some guidence

**Comment by christiangoudreau** [comment]
None took the lead on this yet ;) Unless Maxime started to work on this, you can still take ownership of this! :D

**Comment by olafleur** [comment]
@sambathl I've closed your previous pull request, as it was not relevant anymore in the new code that @meriouma wrote. If you still have this problem, please reopen this issue and/or a pull request. Thanks for your contribution !
