### ISSUE TITLE
Problem in maven build

### ISSUE THREAD

**Issue by ainslec** [ArcBees/gwt-polymer#8]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.13:checkstyle (validate) on project gwt-polymer-parent: Execution validate of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.13:checkstyle failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.13 or one of its dependencies could not be resolved: Could not find artifact com.arcbees:checkstyle:jar:1.1-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots) -> [Help 1]

**Comment by meriouma** [comment]
I've updated the pom, can you pull and try again?

**Comment by ainslec** [comment]
Fast work!

Anyway, tried it, and the build completes successfully now.

Question though, the generated file, gwt-polymer-0.5.5-SNAPSHOT.jar, it doesn't contain any wrapper .java files corresponding to the components being wrapped. Is the creation of the wrapper classes a manual step?

(a small build guide in the readme might help others too :-) )

**Comment by meriouma** [comment]
At the moment it only generates gwt.xml module files. We are still working on the java file generation. Sorry about that!

**Comment by ainslec** [comment]
Ah - I see.

**Comment by olafleur** [comment]
Closing as the problem in the maven build is not there anymore.
